name: amld20_img_clf
channels:
  - conda-forge
  - defaults
dependencies:
  - imageio
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip=19
  - python=3.6
  - scikit-learn>=0.22
  - scipy
  - seaborn
  - tqdm>=4.38
  - pip:
    - google-images-download
    - tensorflow==2.1
    - tensorflow-hub
