name: video-search
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.17.5
  - pandas=0.25.3
  - matplotlib=3.1.2
  - seaborn=0.9
  - jupyterlab=1.1
  - scikit-learn=0.22.1
  - pillow=7.0.0
  - ipywidgets
  - requests
  - nodejs
  - dlib
  - tqdm
  - pip
  - pip:
    - opencv-python
