version: "3.2"
services:
  depiction:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: depiction
    image: drugilsberg/depiction
    ports:
    - "8899:8888"
    environment:
      - JUPYTER_TOKEN=depiction-token
